version: "3"
services:
  ecommerce-node-app:
    image: ecommerce-backend:version1.0
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SECRET_KEY=burhanrajaofficial
      - RAZORPAY_SECRET_KEY=aGDRKs2y0t457rsQIVc5jm0H
      - RAZORPAY_KEY_ID=rzp_test_uZyCrHxTPiUwvc
      - MONGO_DB=burhan_ecommerce
      - MONGO_USER=burhanEcommerce
      - MONGO_PASSWORD=b30496a6cb3ccd29ec8d45b5ad5ed3a0c28089bb
      - MONGO_PORT=27017
      - MONGO_IP=mongo
    command: npm run prod
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=burhanEcommerce
      - MONGO_INITDB_ROOT_PASSWORD=b30496a6cb3ccd29ec8d45b5ad5ed3a0c28089bb
      - MONGO_INITDB_DATABASE=burhan_ecommerce
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:

