version: "3"
services:
  ecommerce-node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=3000
      - SECRET_KEY=
      - RAZORPAY_SECRET_KEY=
      - RAZORPAY_KEY_ID=
      - MONGO_DB=burhan_ecommerce
      - MONGO_USERNAME=
      - MONGO_PASSWORD=
      - MONGO_PORT=27017
      - MONGO_IP=localhost
    command: npm run dev
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=burhanEcommerce
      - MONGO_INITDB_ROOT_PASSWORD=b30496a6cb3ccd29ec8d45b5ad5ed3a0c28089bb
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
